### ISSUE TITLE
python 3.5 .get_children() infinite loop

### ISSUE THREAD

**Issue by pmp-p** [tobspr/LUI#19]
when attempting to add count children on python 3.5 LUI*Layout  class needed to break the loop gone crazy :

```
def __len__(self):
        cnt=0
        for x in self.get_children():
            cnt+=1
            if cnt > 100:
                print('kernel panic !')
                break
```

**Comment by tobspr** [comment]
Not sure if this is still a problem, I believe this might be an issue in interrogate which might have been fixed. I will have a look
