### ISSUE TITLE
std:: namespace removed

### ISSUE THREAD

**Issue by JoelStienlet** [tobspr/LUI#47]
Hello,

Some work has been done recently to remove the inclusion of the std:: namespace by default in panda3d, which is good, but as expected some small corrections may be required.
I suggest some changes to make LUI's sources compile again:

luiInputHandler.h: pmap<int, string> should become pmap<int, std::string> 
luiFontPool.h: pmap<string, PT(DynamicTextFont)> should become pmap<std::string, PT(DynamicTextFont)> 
luiAtlasPool.h: pmap<string, PT(LUIAtlas)> should become  pmap<std::string, PT(LUIAtlas)>
luiBaseElement.h: pmap<string, PT(CallbackObject)> should become pmap<std::string, PT(CallbackObject)>
luiBaseElement.h: don't include unordered_map
config_lui.h : include unordered_map

**Comment by rdb** [comment]
This can be closed as it was fixed by #48.
