### ISSUE TITLE
 GLSL 1.50 - opengl 3.0 fallback 

### ISSUE THREAD

**Issue by pmp-p** [tobspr/LUI#7]
hi, any chance to get support opengl 3.0 as a fallback ?
on radeonsi (hd5770) / ubuntu-mint LTS trusty got errmsg:

> :display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader created-shader:
> 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

as said there https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/137 used
work around to get starting : 
MESA_GL_VERSION_OVERRIDE=3.3 MESA_GLSL_VERSION_OVERRIDE=330 python 01_MinimalExample.py

=> **widgets are ok, but text was unreadable** 
and some :display:gsg:glgsg(error): GL error 0x502 : invalid operation occured

( and no, chipmaker closed driver are not an option )

**Comment by tobspr** [comment]
I think I had issues when using GLSL 1.30 because that GLSL version does not support the "flat" modifier. I will see if I can get it to work with GLSL 1.30 again

**Comment by pmp-p** [comment]
rdb said try change shader version to  "#version 130\n" so i did and it worked fine work now.
but i swear it was all Schwarzbaer fault !

**Comment by rdb** [comment]
@tobspr fwiw "flat" is 1.30+

**Comment by tobspr** [comment]
Ah well, I probably tried out GLSL 1.2 then, if it works fine with 1.3 then I will make it the default, thanks!
